### ISSUE TITLE
HTML inconsistently drops old threaded messages without parent

### ISSUE THREAD

**Issue by ojchase** [DJF3/Webex-Message-space-archiver#5] opened 2021-09-18 01:03 UTC
I asked for 21 messages. The 21 newest messages are in the JSON output correctly. Seventeen are processed normally, including the entirety of their threads. The oldest four, however, are the end of a thread. Message 22 is the start of the thread, but was not requested. (If I configure it to 22, it all works great.)

The four messages are dropped. That might be reasonable. I recognize the challenge here, where you don't have the thread-start message. But output logging might be good (there is none), and the image shows both 17 and 21.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/1005488/133866911-f4135ec3-0a84-4244-8e0b-bd96abcbb9b6.png">

**Comment by DJF3** [comment] 2021-09-21 09:17
Hello @ojchase ,

I think that I know why that happens. I was able to reproduce this behavior in the following scenario:  (with slightly lower numbers to make it easier to document)
maxtotalmessages: **8** 
The messages itself: 

> 9my message number 1
> ____8response1-1
> ____7response1-2
> 6my message number 2
> ____5response2-1
> ____4response2-2
> ____3response2-3
> ____2response2-4
> ____1response2-5

It will take the last 8 messages but can't "process" the last 2 messages (#7 and #8) because _they don't have a parent_. The parent is not included because the max nr of messages is 8 :-) 
In the above scenaro, changing the maxtotalmessages to 9 will fix the problem. 

Is that the case in your scenario?

I never tried to fix this as it did not seem logical to include thread _responses_ without the actual "main message" of that thread.  If you increase the maxtotalmessages by 4 or 5 (depending how long that thread is) it will include the 4 missing messages.

**Comment by ojchase** [comment] 2021-09-28 04:04
Yes, that's the scenario. I recognize this is a strange case and I agree that dropping the messages is a reasonable behavior. My bug report, though, is that the HTML describes the situation inconsistently. The index by month does not include the dropped messages in the count, but the total numbers includes the dropped messages. See the image. It should at least be consistent behavior.

**Comment by DJF3** [comment] 2022-02-10 16:01
@ojchase 
A major update with _many_ fixes, including the fix for this problem has just been posted [here](https://github.com/DJF3/Webex-Message-space-archiver)
Can you let me know if it is fixed?

**Closed as completed** 2022-07-27 07:38 UTC
