### ISSUE TITLE
"Traceback (most recent call last):   File "webex-space-archive.py", line 1232, in <module>     current_step = mycounter/progress_steps ZeroDivisionError: division by zero"

### ISSUE THREAD

**Issue by NikoLiberty** [DJF3/Webex-Message-space-archiver#9] opened 2022-02-08 04:43 UTC
I'm just testing the waters with Cisco Webex, and everything about it makes me happy expect for their strong lack of archiving ability.

I've configured my profile ID (mytoken) as well as the conversation I'm looking to archive as a test (myspaceid) and no matter what I do, it ends with this command:

[Traceback (most recent call last):
  File "webex-space-archive.py", line 1232, in <module>
    current_step = mycounter/progress_steps
ZeroDivisionError: division by zero]

I'm not sure how to move forward from here. And with this script not being exactly common place, there aren't a lot of troubleshooting tips out there.

Any help with this would be greatly appreciated.

**Comment by DJF3** [comment] 2022-02-08 13:59
Hello @NikoLiberty 
It looks like this error is caused by the low number of messages :-)  

I have to do some testing and will then update the code. This week I will publish a new version of the script with a _lot_ of enhancements and fixes.

**Comment by DJF3** [comment] 2022-02-10 15:58
@NikoLiberty 
A major update with _many_ fixes, including the fix for this problem has just been posted [here](https://github.com/DJF3/Webex-Message-space-archiver)
Can you let me know if it is fixed?

**Comment by NikoLiberty** [comment] 2022-02-13 06:45
@DJF3

Hey, again! So, I hadn't had time to mess with the new package until tonight, and I was planning on and hoping that I could give you the victory pose and tell you that it's all good to go, and we were almost there.

The basic tests with the chats I already had went through and worked as expected. But I wanted to triple-check before I gave it my stamp of approval. And it's really good that I did that.

I started a 3rd chat with back and forth messges, more images, animated .gif files, etc.

Now, when I apply the space id of this particular chat, I get this error:

**Traceback (most recent call last):
  File "C:\Users\Arian\AppData\Local\Programs\Python\Python310\webex-space-archive.py", line 1579, in <module>
    stopTimer("generate HTML messages (" + str(round(statTotalMessages, 1)) + ")" + download_stats, dl_duration_total)
NameError: name 'download_stats' is not defined. Did you mean: 'download_avatars'?**

I did try to fix it myself and after removing certain offending lines of code, the archive finished, but the .html file was blank and the only content that downloaded at all were the avatars.

We're **almost** there. I can just feel it!

**Comment by DJF3** [comment] 2022-02-15 10:04
Hello @NikoLiberty 
Can we continue this conversation via Webex messages? You can reach me at duittenb@cisco.com?
It's strange that it stops because "download_stats" is not defined. Why?
Just before this line there is an `IF`, `ELIF`, `ELSE` and all 3 set the `download_stats` variable. So there should be no way for the code to continue without having this variable set. 
Besides that, the value of `download_stats` is purely cosmetical for the performance report.

**Comment by NikoLiberty** [comment] 2022-02-15 10:19
I got you. I'm going to add you right now. Thank you so much for your willingness to help this much.

**Comment by NikoLiberty** [comment] 2022-02-23 08:27
Any update on the timezone issue, out of curiosity?

**Comment by DJF3** [comment] 2022-07-27 07:37
You're welcome @NikoLiberty . The timezone update will be addressed in the next release

**Closed as completed by DJF3** 2022-07-27 07:37 UTC
